# Inspiration: https://github.com/ACCESS-Hive/access-hive.github.io/pull/126
# For security, we do not want to checkout and run code from forks (could lead to secrets being leaked)
# So split documentation build/preview into discrete steps

name: Clean documentation preview

# When a PR is closed, remove the old preview to prevent clutter
on:
  repository_dispatch:
    types: [clean-preview]

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Remove preview
        uses: access-nri/pr-preview-action@v2
        with:
          source-dir: site
          action: remove
          pr-number: ${{ github.event.client_payload.pr }}